PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE score_table(id integer primary key autoincrement,name varchar(16),class varchar(16),score int,check(score >=0 and score <= 100));
INSERT INTO score_table VALUES(1,'王小凤','一班',88);
INSERT INTO score_table VALUES(2,'刘诗迪','一班',70);
INSERT INTO score_table VALUES(3,'李思雨','一班',92);
INSERT INTO score_table VALUES(4,'张文华','二班',55);
INSERT INTO score_table VALUES(5,'张青云','二班',77);
INSERT INTO score_table VALUES(6,'徐文杰','二班',77);
INSERT INTO score_table VALUES(7,'李智瑞','三班',56);
INSERT INTO score_table VALUES(8,'徐雨秋','三班',91);
INSERT INTO score_table VALUES(9,'孙皓然','三班',93);
INSERT INTO score_table VALUES(10,'李春山','三班',57);
COMMIT;
